vascernNew/Models/DiseaseTraslation.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace vascernNew.Models
{
    public class DiseaseTraslation
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public string Name { get; set; }
        public int CultureId { get; set; }
        public Culture Culture { get; set; }
        public int DiseaseId { get; set; }
        public Disease Disease { get; set; }
    }
}

vascernNew/Controllers/DiseaseTraslationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using vascernNew.Data;
using vascernNew.Models;

namespace vascernNew.Controllers
{
    public class DiseaseTraslationsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public DiseaseTraslationsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: DiseaseTraslations
        public async Task<IActionResult> Index(int? id)
        {
            ViewBag.id = id;
            var applicationDbContext = _context.DiseaseTraslation.Where(x=>x.DiseaseId == id).Include(d => d.Culture).Include(d => d.Disease);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: DiseaseTraslations/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var diseaseTraslation = await _context.DiseaseTraslation
                .Include(d => d.Culture)
                .Include(d => d.Disease)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (diseaseTraslation == null)
            {
                return NotFound();
            }

            return View(diseaseTraslation);
        }

        // GET: DiseaseTraslations/Create
        public IActionResult Create(int? id)
        {
            ViewData["CultureId"] = new SelectList(_context.Culture, "Id", "Name");
            ViewData["DiseaseId"] = new SelectList(_context.Disease, "Id", "Name", id);
            ViewData["DiseaseIdSingle"] = id;
            return View();
        }

        // POST: DiseaseTraslations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(DiseaseTraslation diseaseTraslation)
        {
            if (ModelState.IsValid)
            {
                _context.Add(diseaseTraslation);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index), "Diseases");
            }
            ViewData["CultureId"] = new SelectList(_context.Culture, "Id", "Name", diseaseTraslation.CultureId);
            ViewData["DiseaseId"] = new SelectList(_context.Disease, "Id", "Name", diseaseTraslation.DiseaseId);
            ViewData["DiseaseIdSingle"] = diseaseTraslation.DiseaseId;
            return View(diseaseTraslation);
        }

        // GET: DiseaseTraslations/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var diseaseTraslation = await _context.DiseaseTraslation.SingleOrDefaultAsync(m => m.Id == id);
            if (diseaseTraslation == null)
            {
                return NotFound();
            }
            ViewData["CultureId"] = new SelectList(_context.Culture, "Id", "Name", diseaseTraslation.CultureId);
            ViewData["DiseaseId"] = new SelectList(_context.Disease, "Id", "Name", diseaseTraslation.DiseaseId);
            ViewData["DiseaseIdSingle"] = diseaseTraslation.DiseaseId;
            return View(diseaseTraslation);
        }

        // POST: DiseaseTraslations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,CultureId,DiseaseId")] DiseaseTraslation diseaseTraslation)
        {
            if (id != diseaseTraslation.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(diseaseTraslation);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DiseaseTraslationExists(diseaseTraslation.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index), "Diseases");
            }
            ViewData["CultureId"] = new SelectList(_context.Culture, "Id", "Name", diseaseTraslation.CultureId);
            ViewData["DiseaseId"] = new SelectList(_context.Disease, "Id", "Name", diseaseTraslation.DiseaseId);
            ViewData["DiseaseIdSingle"] = diseaseTraslation.DiseaseId;
            return View(diseaseTraslation);
        }

        // GET: DiseaseTraslations/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var diseaseTraslation = await _context.DiseaseTraslation
                .Include(d => d.Culture)
                .Include(d => d.Disease)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (diseaseTraslation == null)
            {
                return NotFound();
            }

            return View(diseaseTraslation);
        }

        // POST: DiseaseTraslations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var diseaseTraslation = await _context.DiseaseTraslation.SingleOrDefaultAsync(m => m.Id == id);
            _context.DiseaseTraslation.Remove(diseaseTraslation);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index), "Diseases");
        }

        private bool DiseaseTraslationExists(int id)
        {
            return _context.DiseaseTraslation.Any(e => e.Id == id);
        }
    }
}

vascernNew/Views/DiseaseTraslations/Create.cshtml
@model vascernNew.Models.DiseaseTraslation

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>DiseaseTraslation</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input asp-for="Id" class="form-control" value="0" type="hidden" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CultureId" class="control-label">Language</label>
                <select asp-for="CultureId" class="form-control" asp-items="ViewBag.CultureId"></select>
            </div>
            <div class="form-group" style="display: none">
                <label asp-for="DiseaseId" class="control-label"></label>
                <select asp-for="DiseaseId" class="form-control" asp-items="ViewBag.DiseaseId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-block btn-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="DiseaseTraslations" asp-action="Index" asp-route-id="@ViewBag.DiseaseIdSingle">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

vascernNew/Views/DiseaseTraslations/Delete.cshtml
@model vascernNew.Models.DiseaseTraslation

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DiseaseTraslation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Culture)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Culture.Id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Disease)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Disease.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-block btn-danger" />
    </form>
</div>

vascernNew/Views/DiseaseTraslations/Details.cshtml
@model vascernNew.Models.DiseaseTraslation

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>DiseaseTraslation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Culture)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Culture.Id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Disease)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Disease.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

vascernNew/Views/DiseaseTraslations/Edit.cshtml
@model vascernNew.Models.DiseaseTraslation

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>DiseaseTraslation</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CultureId" class="control-label">Language</label>
                <select asp-for="CultureId" class="form-control" asp-items="ViewBag.CultureId"></select>
                <span asp-validation-for="CultureId" class="text-danger"></span>
            </div>
            <div class="form-group" style="display: none">
                <label asp-for="DiseaseId" class="control-label" ></label>
                <select asp-for="DiseaseId" class="form-control" asp-items="ViewBag.DiseaseId"></select>
                <span asp-validation-for="DiseaseId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-block btn-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="DiseaseTraslations" asp-action="Index" asp-route-id="@ViewBag.DiseaseIdSingle">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

vascernNew/Views/DiseaseTraslations/Index.cshtml
@model IEnumerable<vascernNew.Models.DiseaseTraslation>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create"  asp-route-id="@ViewBag.id">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Language
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Disease)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Culture.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Disease.Name)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a class="delete" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>