vascernNew/Controllers/CulturesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using vascernNew.Data;
using vascernNew.Models;

namespace vascernNew.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CulturesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CulturesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Cultures
        public async Task<IActionResult> Index()
        {
            return View(await _context.Culture.ToListAsync());
        }

        // GET: Cultures/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var culture = await _context.Culture
                .SingleOrDefaultAsync(m => m.Id == id);
            if (culture == null)
            {
                return NotFound();
            }

            return View(culture);
        }

        // GET: Cultures/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Cultures/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Culture culture)
        {
            if (ModelState.IsValid)
            {
                _context.Add(culture);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(culture);
        }

        // GET: Cultures/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var culture = await _context.Culture.SingleOrDefaultAsync(m => m.Id == id);
            if (culture == null)
            {
                return NotFound();
            }
            return View(culture);
        }

        // POST: Cultures/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Culture culture)
        {
            if (id != culture.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(culture);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CultureExists(culture.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(culture);
        }

        // GET: Cultures/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var culture = await _context.Culture
                .SingleOrDefaultAsync(m => m.Id == id);
            if (culture == null)
            {
                return NotFound();
            }

            return View(culture);
        }

        // POST: Cultures/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var culture = await _context.Culture.SingleOrDefaultAsync(m => m.Id == id);
            _context.Culture.Remove(culture);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CultureExists(int id)
        {
            return _context.Culture.Any(e => e.Id == id);
        }
    }
}

vascernNew/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<!--
* CoreUI - Free Bootstrap Admin Template
* Copyright (c) 2018 creativeLabs Łukasz Holeczek
* Licensed under MIT (https://coreui.io/license)
-->

<html lang="en">
<head>
    <base href="./">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Vascern API</title>
    <!-- Icons-->
    <link rel="icon" type="image/ico" href="~/img/favicon.ico" sizes="any" />
    <!-- Main styles for this application-->
    <link href="~/css/style.css" rel="stylesheet">
    <link href="~/vendors/pace-progress/css/pace.min.css" rel="stylesheet">
    <!-- Global site tag (gtag.js) - Google Analytics-->
</head>
<body class="app header-fixed sidebar-fixed aside-menu-fixed sidebar-lg-show">
    <header class="app-header navbar">
        <button class="navbar-toggler sidebar-toggler d-lg-none mr-auto" type="button" data-toggle="sidebar-show">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="#">
            <img class="navbar-brand-full" src="~/img/brand/logo.svg" width="89" height="25" alt="CoreUI Logo">
            <img class="navbar-brand-minimized" src="~/img/brand/sygnet.svg" width="30" height="30" alt="CoreUI Logo">
        </a>
        @await Html.PartialAsync("~/Views/Shared/_LoginPartial.cshtml")
    </header>
    <div class="app-body">
        <div class="sidebar">
            <nav class="sidebar-nav">
                <ul class="nav">
                    <li><a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Dashboard</a></li>
                    <li><a class="nav-link" asp-area="" asp-controller="Cultures" asp-action="Index">Languages</a></li>
                    <li><a class="nav-link" asp-area="" asp-controller="Diseases" asp-action="Index">Diseases</a></li>
                    <li><a class="nav-link" asp-area="" asp-controller="Associations" asp-action="Index">Association</a></li>
                    <li><a class="nav-link" asp-area="" asp-controller="HcpCenters" asp-action="Index">HCP Centers</a></li>
                    <li><a class="nav-link" asp-area="" asp-controller="DiseaseCenters" asp-action="Index">Disease => HCP</a></li>
                    <li><a class="nav-link" asp-area="" asp-controller="DiseaseAssociations" asp-action="Index">Disease <=> Association</a></li>
                    <li><a class="nav-link" asp-area="" asp-controller="AssociationHcps" asp-action="Index">Association <=> HCP</a></li>
                    @*<li><a class="nav-link" asp-area="" asp-controller="CenterEmails" asp-action="Index">Email Centers</a></li>
        <li><a class="nav-link" asp-area="" asp-controller="CenterPhones" asp-action="Index">Phone Centers</a></li>*@
                    <li><a class="nav-link" asp-area="" asp-controller="Account" asp-action="Register">Create new user</a></li>
                    <li><a class="nav-link" asp-area="" asp-controller="Home" asp-action="UserList">User list</a></li>
                </ul>
            </nav>
            <button class="sidebar-minimizer brand-minimizer" type="button"></button>
        </div>
        <main class="main">
            <!-- Breadcrumb-->
            <ol class="breadcrumb">
                <li class="breadcrumb-item">Home</li>
                <li class="breadcrumb-item">
                    <a href="javascript:void(0)">Admin</a>
                </li>
            </ol>
            <div class="container-fluid">
                <div class="animated fadeIn">
                    <div class="row">
                        <div class="col-lg-12">
                            @RenderBody()
                        </div>
                        <!-- /.col-->
                    </div>

                    <!-- /.row-->
                </div>
            </div>
        </main>

    </div>
    <footer class="app-footer">
        <div>
            <a href="https://coreui.io">Vascern</a>
            <span>&copy; 2019 vascern.</span>
        </div>
        <div class="ml-auto">
            <span>Powered by</span>
            <a href="javscript:void(0)">Vascern</a>
        </div>
    </footer>
    <!-- CoreUI and necessary plugins-->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>